"""Domain event type names, mirrored from docs/architecture.md Section I.
The WebSocket gateway (Step 6) fans these out verbatim to subscribed clients."""


class EventType:
    MARKET_CREATED = "MARKET_CREATED"
    MARKET_UPDATED = "MARKET_UPDATED"
    MARKET_SUSPENDED = "MARKET_SUSPENDED"
    MARKET_REOPENED = "MARKET_REOPENED"
    MARKET_CLOSED = "MARKET_CLOSED"
    EVENT_STATUS_CHANGED = "EVENT_STATUS_CHANGED"
    ODDS_UPDATED = "ODDS_UPDATED"
    ORDER_PLACED = "ORDER_PLACED"
    ORDER_MATCHED = "ORDER_MATCHED"
    ORDER_PARTIALLY_MATCHED = "ORDER_PARTIALLY_MATCHED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    BET_ACCEPTED = "BET_ACCEPTED"
    BET_REJECTED = "BET_REJECTED"
    BET_SETTLED = "BET_SETTLED"
    BALANCE_UPDATED = "BALANCE_UPDATED"
    MARKET_SETTLED = "MARKET_SETTLED"
    MATCH_STATE_UPDATED = "MATCH_STATE_UPDATED"
